<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_scan_radius" value="0.05"/>
    <xacro:property name="base_scan_length" value="0.05"/>


    <link name="base_scan_link">
        <visual>
            <geometry>
                <cylinder radius="${base_scan_radius}" length="${base_scan_length}"/>
            </geometry>
            <origin xyz="0 0 ${base_scan_length/2.0}" rpy="0 0 0"/>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${base_scan_radius}" length="${base_scan_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${base_scan_radius}" l="${base_scan_length}"
                                o_xyz="0 0 ${base_scan_length / 2.0}" o_rpy="0 0 0" />
    </link>

    <joint name="base_scan_joint" type="fixed"> 
        <parent link="arm_base_link"/>
        <!-- <parent link="base_link"/> -->

        <child link="base_scan_link"/>
        <origin xyz="${arm_base_width/4.0} 0 ${arm_base_height/2.0}" rpy="0 0 0"/>
    </joint>


    <gazebo reference="base_scan_link">
        <sensor name="base_scan_sensor" type="gpu_lidar">
            <pose> 0 0 0 0 0 0 </pose>
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <topic>model/car_washing_robot/scan</topic>
            <!-- <topic>/scan</topic> -->
            <!-- <frame_id>base_scan_link</frame_id> -->
            <frame>base_scan_link</frame>
            <lidar>
                <scan>
                    <horizontal>
                    <samples>720</samples>
                    <resolution>1</resolution>
                    <min_angle>-2.30</min_angle> <!-- -131.78 degrees-->
                    <max_angle>2.30</max_angle>  <!--  131.78 degrees-->
                    </horizontal>
                </scan>
                <range>
                    <min>0.05</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </lidar>
        </sensor>
    </gazebo>

</robot>

