<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="soap_tank_length" value="0.25"/>
    <xacro:property name="soap_tank_width" value="0.08"/>
    <xacro:property name="soap_tank_height" value="0.05"/>

    <link name="soap_tank_link">
        <visual>
            <geometry>
                <box size="${soap_tank_length} ${soap_tank_width} ${soap_tank_height}"/>
            </geometry>
            <origin xyz="0 0 ${soap_tank_height/2.0}" rpy="0 0 1.5708" />
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <box size="${soap_tank_length} ${soap_tank_width} ${soap_tank_height}"/>
            </geometry>
            <origin xyz="0 0 ${soap_tank_height/2.0}" rpy="0 0 1.5708" />
        </collision>
        <xacro:box_inertia m="5" x="${soap_tank_length}" y="${soap_tank_width}" z="${soap_tank_height}"
                          o_xyz="0 0 0" o_rpy="0 0 0"/>
    </link>


    <joint name="base_soap_tank" type="fixed">
        <parent link="base_link"/>
        <child link="soap_tank_link"/>
        <origin xyz="${-base_length/2.0 + water_tank_width/2.0} 0 ${base_height + water_tank_height}" rpy="0 0 0"/>
    </joint>

</robot>