<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


  <!-- Arm Base Link

  <link name="arm_base_link">
    <visual>
      <geometry>
        <cylinder radius="0.5" length="0.05"/>
      </geometry>
      <material name="grey"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.5" length="0.05"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link> -->


<!--Arm base link2-->

    <xacro:property name="arm_base_length" value="0.6" />
    <xacro:property name="arm_base_width" value="0.8" />
    <xacro:property name="arm_base_height" value="0.26" />

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="0.5" x="${arm_base_length}" y="${arm_base_width}" z="${arm_base_height}"
                           o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>


  <!-- Links and Joints -->

  <xacro:macro name="arm_link" params="link_name parent_name xyz rpy length radius mass ixx iyy izz">
    <link name="${link_name}">
      <visual>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <material name="blue"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
      </collision>
      <xacro:cylinder_inertia m="0.3" r="${radius}" l="${length}"
                                o_xyz="0 0 ${length / 2.0}" o_rpy="0 0 0" />
    </link>


    <joint name="${link_name}_joint" type="revolute">
      <parent link="${parent_name}"/>
      <child link="${link_name}"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="100" />
      <dynamics friction="1.0" damping="5.0" />
    </joint>
  </xacro:macro>


     <!-- Z-axis Rotating Link and Joint -->

  <xacro:macro name="z_axis_arm_link" params="link_name parent_name xyz rpy length radius mass ixx iyy izz">
    <link name="${link_name}">
      <visual>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <material name="blue"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
      </collision>
      <xacro:cylinder_inertia m="0.3" r="${radius}" l="${length}"
                                o_xyz="0 0 ${length / 2.0}" o_rpy="0 0 0" />
    </link>


    <joint name="${link_name}_joint" type="revolute">
      <parent link="${parent_name}"/>
      <child link="${link_name}"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="100" />
      <dynamics friction="1.0" damping="5.0" />
    </joint>
  </xacro:macro>

  <!-- Instantiate 6 links -->
  <xacro:z_axis_arm_link link_name="link_1" parent_name="arm_base_link" xyz="${arm_base_width/4.0} 0 0.13" rpy="0 0 0" length="0.2" radius="0.06" mass="1.0" ixx="0.005" iyy="0.005" izz="0.005"/>
  <xacro:arm_link link_name="link_2" parent_name="link_1" xyz="0 0 0.2" rpy="0 0 0" length="0.2" radius="0.05" mass="0.8" ixx="0.003" iyy="0.003" izz="0.003"/>
  <xacro:arm_link link_name="link_3" parent_name="link_2" xyz="0 0 0.2" rpy="0 0 0" length="0.15" radius="0.04" mass="0.6" ixx="0.002" iyy="0.002" izz="0.002"/>
  <xacro:z_axis_arm_link link_name="link_4" parent_name="link_3" xyz="0 0 0.15" rpy="0 0 0" length="0.15" radius="0.04" mass="0.5" ixx="0.0015" iyy="0.0015" izz="0.0015"/>
  <xacro:arm_link link_name="link_5" parent_name="link_4" xyz="0 0 0.15" rpy="0 0 0" length="0.1" radius="0.03" mass="0.3" ixx="0.001" iyy="0.001" izz="0.001"/>
  <xacro:arm_link link_name="link_6" parent_name="link_5" xyz="0 0 0.1" rpy="0 0 0" length="0.1" radius="0.03" mass="0.2" ixx="0.0008" iyy="0.0008" izz="0.0008"/>


    <!-- Camera at the end

  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <xacro:box_inertia m="0.1" x="0.05" y="0.05" z="0.05"
                          o_xyz="0 0 0" o_rpy="0 0 0"/>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="link_6"/>
    <child link="camera_link"/>
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
  </joint> -->

</robot>