<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="water_tank_length" value="${base_width}"/>
    <xacro:property name="water_tank_width" value="0.40"/>
    <xacro:property name="water_tank_height" value="0.26"/>

    <link name="water_tank_link">
        <visual>
            <geometry>
                <box size="${water_tank_length} ${water_tank_width} ${water_tank_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 1.5708" />
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${water_tank_length} ${water_tank_width} ${water_tank_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 1.5708" />
        </collision>
        <xacro:box_inertia m="5" x="${water_tank_length}" y="${water_tank_width}" z="${water_tank_height}"
                          o_xyz="0 0 0" o_rpy="0 0 0"/>
    </link>

    <joint name="base_water_tank" type="fixed">
        <parent link="base_link"/>
        <child link="water_tank_link"/>
        <origin xyz="${-base_length/2.0 + water_tank_width/2.0} 0 ${base_height + water_tank_height/2.0}" rpy="0 0 0"/>
    </joint>

</robot>