
APPROACH_SPEED = 0.2
TARGET_DISTANCE = 0.7

WALL_TARGET_DISTANCE = 0.5
WALL_FOLLOW_SPEED = 0.15
WALL_DISTANCE_TOLERANCE = 0.1
STEERING_GAIN = 0.3

CORNER_DETECTION_THRESHOLD = 2.0
TURNING_SPEED = 0.5
TURN_DURATION = 3.2

ZERO = 0.0
MAX_DISTANCE = 999.0

OBSTACLE_STOP_DISTANCE = 0.3